on: [push]
name: Teste
jobs:
  Build_Deploy:
    runs-on: windows-latest
    name: A job to run VSTest
    steps:
      - uses: actions/checkout@v2

      - name: Create custom environment
        run: |
          $short = git rev-parse --short HEAD | Out-String
          echo "RELEASE_NUMBER=1.0.0-$short" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          $location = (Resolve-Path .\).Path
          echo "BUILD_RELESE_PATH=$location\release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore
        run: nuget restore

      - name: Build test projects
        run: |
             Get-ChildItem -Include *.csproj -Recurse -Path .\test\ | 
             ForEach-Object -ErrorAction Stop -Process { 
                msbuild /p:Configuration=Release,RestorePackages=false $_.FullName 
                if ($? -eq $false) {
                    throw "Build error in: $_";
                }
             }

      - name: Run tests
        uses: microsoft/vstest-action@v1.0.0
        with:
           testAssembly: '**\bin\Release\*Test.dll'
           searchFolder:  .\test\
           runInParallel: true
